# Generated by Django 3.2 on 2023-05-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='release_year',
            new_name='year',
        ),
    ]
